### ISSUE TITLE
numFmt does not add a dollar sign in front of my munber

### ISSUE THREAD

**Issue by MajdMaghamez** [securedeveloper/react-data-export#119]
I am trying to format a multidata set 
i normalized my data to look exactly like the example on this link: 
https://github.com/securedeveloper/react-data-export/blob/master/examples/styled_excel_sheet.md
and in style element i am doing the following:
style = { font: { color: { rgb: "FF000000" } }, numFmt : "$0.00"};
but once you export that excel file non of my values have a $ sign
I noticed the color has changed so that is working.
can you provide examples on using numFmt please ?

Thanks

**Comment by securedeveloper** [comment]
Please use a formated dataset in this case,

**Comment by atefBB** [comment]
> Please use a formated dataset in this case,

Can you give me more info about that ? I'm facing the same issue ! Thanks.
