### ISSUE TITLE
xlsx dependencies were not downloaded on the older version

### ISSUE THREAD

**Issue by ipramono** [securedeveloper/react-data-export#123]
* Give a brief explanation of the issue, suggestion or feature to request.
I am using version 0.3.7, 7 days ago our deployment was still successful. It downloaded the xlsx package in the npm list. However, today when trying to run the same deployment without any change, I noticed the xlsx package is missing from the npm list.
Error message:
ERROR in ./node_modules/react-data-export/dist/ExcelPlugin/components/ExcelFile.js
20:05:08.308 Module not found : error : Can't resolve 'xlsx' in 'D:\GOCD\GoAgent2\pipelines\IMT_Web\Source\src\Web\node_modules\react-data-export\dist\ExcelPlugin\components' [D:\GOCD\GoAgent2\pipelines\IMT_Web\Source\src\Web\ImtWeb.csproj]
20:05:08.308   resolve 'xlsx' in 'D:\GOCD\GoAgent2\pipelines\IMT_Web\Source\src\Web\node_modules\react-data-export\dist\ExcelPlugin\components'
20:05:08.308     Parsed request is a module
20:05:08.309     using description file: D:\GOCD\GoAgent2\pipelines\IMT_Web\Source\src\Web\node_modules\react-data-export\package.json (relative path: ./dist/ExcelPlugin/components)

**Comment by securedeveloper** [comment]
@ipramono I made a new release yesterday, if you're still using the old version, please update to the new one, incase the problem still persist please re-open the issue, I will be happy to help.

**Comment by ipramono** [comment]
Hi @securedeveloper.
Fyi, when I used the latest one, it is complaining the same thing. It asked for xlsx, even though it was called by tempa-xlsx.
When I checked, it seems like tempa-xlsx requires xlsx 0.8.20 which is not existent anymore:
https://www.npmjs.com/package/xlsx

I fixed it by using the old version: `react-data-export@^0.3.7`, but add `xlsx@^0.9.0` in my packages.json

**Comment by securedeveloper** [comment]
> Hi @securedeveloper.
> Fyi, when I used the latest one, it is complaining the same thing. It asked for xlsx by tempa-xlsx.
> When I checked, it seems like tempa-xlsx requires xlsx 0.8.20 which is not existent anymore:
> https://www.npmjs.com/package/xlsx
> 
> I fixed it by using the old version: `react-data-export: "^0.3.7"`, but add `xlsx: "^0.9.0"` in my packages.json

thanks, I already updated the package and will publish it today.

**Comment by plainnany** [comment]
@securedeveloper hi, I use `react-data-export@0.6.0`, the question is stil existent

**Comment by ipramono** [comment]
@plainnany If you want to follow my workaround, here it is:
I used: "react-data-export": "^0.3.7",
and add: "xlsx": "^0.9.0" on the dependencies.
