### ISSUE TITLE
Can not see fill and font colors in .xlsx file with Microsoft excel when exporting

### ISSUE THREAD

**Issue by mohitkyadav** [securedeveloper/react-data-export#144]
#### My reason:
Can not see fill and font colors in .xlsx file with Microsoft excel when exporting using react-data-export
https://stackoverflow.com/questions/64673968/can-not-see-fill-and-font-colors-in-xlsx-file-with-mirosoft-excel-when-exportin
#### Steps to reproduce:
1. Export some styled data to excel file, make sure you use some kind of font color or fill color in styles.
2. Open the same file in google sheets and microsoft excel
3. Notice the color styles are only visible in google sheets and MS excel replaces black with any color styling
**MS excel**
![image](https://user-images.githubusercontent.com/25580776/98075209-f8e85900-1e91-11eb-8537-8cba672edaa5.png)
**Google Sheets**
![image](https://user-images.githubusercontent.com/25580776/98075246-09003880-1e92-11eb-8d1d-f1d0f53f9362.png)

#### Lib Version:
0.6.0

**Comment by YVeselovskyi** [comment]
I have same issue

**Comment by mohitkyadav** [comment]
This is fixed, check my answer @YVeselovskyi  https://stackoverflow.com/questions/64673968/can-not-see-fill-and-font-colors-in-xlsx-file-with-mirosoft-excel-when-exportin/64678030#64678030
