### ISSUE TITLE
Styling the download Button and changing text ?

### ISSUE THREAD

**Issue by HachimDev** [securedeveloper/react-data-export#15]
Is it possible to style the download button along with the text inside please ?

**Comment by surndraraj3** [comment]
Hi @HachimDev have you got any solution for styling and modify the text

**Comment by HachimDev** [comment]
unfortunately not. I had to create a new component using xlsx and file-saver from scratch

**Comment by securedeveloper** [comment]
Sorry guys about the delay, Was busy with another library. You will have a solution by the end of this week.

**Comment by abiodunsulaiman694** [comment]
I was able to style the button and the text.
ExcelFile.js accepts 2 props that has default values: `filename` and `element`

The default props from the source code: `ExcelFile.js` are:
`ExcelFile.defaultProps = {
    filename: "Download.xlsx",
    element: _react2.default.createElement(
        "button",
        null,
        "Download"
    )
};`

To override it, simply pass in your own props:
` <ExcelFile filename="Report Validation" element={(<Button bsStyle="info">
						                                            Download Report
						                                        </Button>)}>`

Please, note that, in my case, I already have, `Button` component imported.
You can use your own component. [react-bootstrap](https://github.com/react-bootstrap/react-bootstrap) comes handy, if interested

**Comment by securedeveloper** [comment]
@surndraraj3 hopefully your issue is solved now, This week I am working on it, going to release a minor change to support multiple sheets in Excel file. Just found a lot of things to improve and in coming weeks you guys will have some good stuff 🍯

**Comment by surndraraj3** [comment]
@abiodunsulaiman694  I have implemented multiple sheets in a single excel file here is the example, By using your libraray
<ExcelFile filename="Master Data.xlsx">
  {
	this.state.masterDataDownload
	?
	(this.state.masterDataDownload.map((values) => {
	  console.log('values', values);
	  return (
		<ExcelSheet data={values.masterDataType.names} name={values.masterDataType.code}>
		  <ExcelColumn label="code" value="code" />
		  <ExcelColumn label="name" value="name" />
		</ExcelSheet>
	  );
	}))
	:
	''
  }
</ExcelFile>
