### ISSUE TITLE
Pass multiple data sources into ExcelSheet

### ISSUE THREAD

**Issue by abiodunsulaiman694** [securedeveloper/react-data-export#16]
Great job on this package.

I need to pass multiple data sources into ExcelSheet Component, as the sheet is to comprise of many tables. And possible use basic styling like, bold.

Could you, please, help.

Thank you.

**Comment by securedeveloper** [comment]
Hey I got your request, I have progress on that. I will finish this week and you will have a nice and clean solution latest by this Monday.

Thank you for using this library.

**Comment by abiodunsulaiman694** [comment]
@securedeveloper Thanks a bunch. Expecting.

**Comment by securedeveloper** [comment]
@abiodunsulaiman694  issue has been resolved with #17 , will update documentation soon.

**Comment by abiodunsulaiman694** [comment]
Hi, @securedeveloper . Well done. Could you, please, give an example of how multiple datasets can be passed into one ExcelSheet.

I'm passing it in as an array, but getting **invalid file** downloaded. My code:
`<ExcelSheet data={[dataSet1, dataSet2]} name="Report">`

I need the ExcelSheet to have multiple tables.

Thank you.

**Comment by abiodunsulaiman694** [comment]
@securedeveloper Found the solution in the docs. Thanks

**Comment by meharfatimakhan** [comment]
Hi, is there a way to export data to 2 sheets in the same file?
