### ISSUE TITLE
File exports without xlsx extension

### ISSUE THREAD

**Issue by abiodunsulaiman694** [securedeveloper/react-data-export#21]
I'm saving a file with multiple datasets as it is in the docs. The data exports but without the xlsx extension, hence reads as invalid.
If I rename the file with the xlsx extension, it opens well with excel.
I use create-react-app, so I don't have access to the webpack config.
Thanks for your help. Expecting.

**Comment by securedeveloper** [comment]
Hello, Thank you for letting me know about this issue, You can pass name as prop to `ExcelFile`
For example,
```javascript
<ExcelFile name={"Employees.xlsx"} ... />
```,

In next patch, I will put extension by default so that if there is no extension defined, It will take assign `.xlsx` automatically.

**Comment by abiodunsulaiman694** [comment]
Thanks. Fixed. Appreciate your swift response. Great job. reat packae.
