### ISSUE TITLE
Styling exported table

### ISSUE THREAD

**Issue by abiodunsulaiman694** [securedeveloper/react-data-export#22]
Hello, any chance of being able to style the exported data? I would like to create a band for the header column to differentiate it. Probably style multiple datasets differently, possibly add caption for data and brand the document with the organization name and logo. Thanks. Love this package.

**Comment by securedeveloper** [comment]
Hello, Yes it is possible but it need a big change, I am using `js-xlsx` library for the movement for exporting data and they don't have a way to style it. But I already got a solution and will implement this week. Soon you will have a solution for that.

Just stay tuned.

**Comment by abiodunsulaiman694** [comment]
Thanks. Expecting

**Comment by alexeymakarov90** [comment]
Is there any chance for a colspan ?:)

**Comment by securedeveloper** [comment]
Hello @alexeymakarov90 we have some major improvements in pipeline which includes but not limited to "Exporting styled data", "ColSpan and RowSpan" operations, "Formulas support" and so on.

Stay tuned.

**Comment by quarleswn** [comment]
Any further news on this? Is basic styling such as bold/italic also still in the pipeline? Or is it already possible in the current version?

**Comment by anovags** [comment]
maybe there's a workaround for current version, for a simple bold/italic styling perhaps?

**Comment by securedeveloper** [comment]
@anovags @quarleswn @alexeymakarov90 all requests you guys made are already implemented (But unfortunately my reviewer is not ready to review changes yet, I will wait for 1 more day otherwise will by bass and release those changes)

**Comment by colinrcummings** [comment]
@securedeveloper, this is a great library. looking forward to these changes.

**Comment by jamalashrafi** [comment]
Hi Sulaiman when will u check in the updated code, we are waiting .

**Comment by dannegm** [comment]
I thnik that, `js-xlsx` have options to apply styles to the cells

https://github.com/SheetJS/js-xlsx/blob/master/docbits/64_cellprops.md
https://github.com/SheetJS/js-xlsx/blob/master/docbits/51_cell.md

**Comment by securedeveloper** [comment]
@abiodunsulaiman694 @alexeymakarov90 @quarleswn @anovags @colinrcummings @jamalashrafi @dannegm this feature is implemented. Please feel free to try and let us know about your feedback.

**Comment by colinrcummings** [comment]
Thank you, @securedeveloper. I just updated to 0.3.7 and am adding style to an export. Is there a way to set column and row widths ([AutoFit Column Width](https://support.office.com/en-us/article/change-the-column-width-and-row-height-72f5e3cc-994d-43e8-ae58-9774a0905f46) is what I'm looking for at the moment)?

**Comment by securedeveloper** [comment]
Hi @colinrcummings it is a good feature, I'm looking into it.

**Comment by colinrcummings** [comment]
Hey, @securedeveloper. The [original fork](https://github.com/protobi/js-xlsx) of [`SheetJS`](https://github.com/SheetJS/js-xlsx) that [you forked](https://github.com/securedeveloper/js-xlsx) for `react-data-export` [isn't actively maintained](https://github.com/protobi/js-xlsx/issues/90#issuecomment-371560391) as styles were implemented in [`SheetJS Pro`](http://sheetjs.com/pro). Both forks don't have style support for anything more than cells. Have you seen [exceljs](https://github.com/guyonroche/exceljs)? It's actively maintained and has [style support](https://github.com/guyonroche/exceljs#styles) for cells, rows and columns.

**Comment by securedeveloper** [comment]
Hi @colinrcummings, I just checked the references you mentioned, the idea of using a fork of `xlsx` library was to make sure we do not break things if something goes wrong with that repo, we have a plan to reference back to original repo as they are still working on this support.

Also, `Autofit Column Width` is possible if we go with content length, I already tested it few days ago. I just need to make sure some performance checks and if everything works we will have this support out of the box by our library not changing anything in `xlsx`.

By the way you can follow our ongoing tasks and plans [here](https://github.com/securedeveloper/react-data-export/projects/1)

**Comment by colinrcummings** [comment]
Sounds good, @securedeveloper. Being able to style columns would be great. Thanks again for your work on this.

**Comment by pedrobrost** [comment]
It would very nice to have the AutoFit feature :)

**Comment by gmonte** [comment]
Hi guys. About AutoFit, any news?

**Comment by diegohdez90** [comment]
Hi programmers, it would be nice if add `style` for `data` key in `ExcelSheet Props`, what do you think?

**Comment by vvicario** [comment]
HI! About AutoFit, any news?

**Comment by securedeveloper** [comment]
Hi @uditdubey, it's possible to apply `colspan` but unfortunately, the functionality is not supported yet with the current version. Will keep in the agenda for this year.

**Comment by uditdubey** [comment]
Hi @securedeveloper i somehow managed to style the table to look like colspan. Is there anyway to style the column name border. As the style attribute works only for data array and not for column name. Stuck !! 
![capture](https://user-images.githubusercontent.com/41045663/50639429-789bf880-0f87-11e9-9c23-b792b7bd5d03.PNG)

Thanks !!

**Comment by Dhara159** [comment]
> Hi @securedeveloper i somehow managed to style the table to look like colspan. Is there anyway to style the column name border. As the style attribute works only for data array and not for column name. I want to remove the left and right borders. Stuck !!
> ![capture](https://user-images.githubusercontent.com/41045663/50639429-789bf880-0f87-11e9-9c23-b792b7bd5d03.PNG)
> 
> Thanks !!

Hey @uditdubey Can you provide some hint on how you managed to do colSpan with header? I am using v0.4.2. Is repo support available for colspan till now?

**Comment by Natalyiia** [comment]
> Hi @securedeveloper i somehow managed to style the table to look like colspan. Is there anyway to style the column name border. As the style attribute works only for data array and not for column name. I want to remove the left and right borders. Stuck !! ![capture](https://user-images.githubusercontent.com/41045663/50639429-789bf880-0f87-11e9-9c23-b792b7bd5d03.PNG)
> 
> Thanks !!

HI @uditdubey could you please describe how you did this?
