### ISSUE TITLE
please provide some examples how properly use it

### ISSUE THREAD

**Issue by annslittleflower** [securedeveloper/react-data-export#23]
wrote a function, calling it and nothing happens, no error and no anything else

    const excel = () => {
      return (
        <ExcelFile>
           <ExcelSheet data={this.state.entities.results} name="Orders">
               <ExcelColumn label="Name" value="name" />
               <ExcelColumn label="Created at" value="createdAt" />
           </ExcelSheet>
         </ExcelFile>
      );
    };
 
    return excel();

**Comment by securedeveloper** [comment]
Hey man, Thank for opening and issue,

Could you please share how you are importing modules `ExcelFile`, `ExcelSheet` and `ExcelColumn` from the library. As you mentioned you are not getting any error it means there is no data being passed to the library. Please make sure by logging that you are passing data correctly.

And in my opinion passing data through `state` variable is not a very good practice.

**Comment by annslittleflower** [comment]
import { default as ExcelFile, ExcelSheet, ExcelColumn } from "react-data-export";

thats my imports
but how else should i pass data?

**Comment by securedeveloper** [comment]
Well, Imports seems fine, I am quite sure about the data you are passing, you are not getting data in your library.

**Comment by securedeveloper** [comment]
Just before return try to log data you are passing to library.

**Comment by annslittleflower** [comment]
on logs i got the data

**Comment by annslittleflower** [comment]
maybe its because object in JS being passed by reference?

**Comment by securedeveloper** [comment]
It should not be a problem, anyways there are 2 ways for using this library, you can try using the 2nd method, i.e
```javascript
const data = [
    {
        columns: ["Name", "Created At"],
        data: [
            ["Name1", "28-01-2018"],
            ["Name2", "27-01-2018"]
        ]
    };

//then use it like this,
<ExcelFile>
      <ExcelSheet dataSet={data} name="YourExcelFileName" />
</ExcelFile>
```

Also if possible can you please share structure of your data (when you logged) is it array of objects or array of arrays.

**Comment by annslittleflower** [comment]
![image](https://user-images.githubusercontent.com/18059716/35572650-bdc56d42-05dd-11e8-913f-63a1dd44541e.png)

**Comment by annslittleflower** [comment]
this is after your last comment, but still nothing works((((

**Comment by securedeveloper** [comment]
Ok I got it, So here is the issue, 
Please pass `<ExcelSheet data={this.state.entities.results[0].data} ...` and it should work with your original code. 

Right now, you are passing it as a whole object and when you try to download it iterate through the object and try to find keys `name` and `createdAt` on `results` object, but your results object is an array where on `0` index you have an object with keys `columns` and `data`, and all you need to pass is that `data` out of your whole result object.

Hopefully this should solve your issue.

**Comment by securedeveloper** [comment]
Let me know if it works for you,  I will update documentation afterwards for better understanding.

**Comment by annslittleflower** [comment]
thats the code: 
    let data = [
      {
        columns: ['name', 'createdAt'],
        data: this.state.entities.results,
      }
    ]

    const excel = () => {
      console.log(data);
      return (
        <ExcelFile>
           <ExcelSheet dataSet={data} name="Orders"/ >
         </ExcelFile>
      );
    };

    return excel();

previous console log i sent you was from this code, so i dont have this.state.entities.results[0].data

**Comment by annslittleflower** [comment]
data: [
            ["Name1", "28-01-2018"],
            ["Name2", "27-01-2018"]
        ]

**Comment by securedeveloper** [comment]
Actually if you wanna try the 2nd method it is for the purpose if your data in not in `Object` form, So all you have to do is have an array of array in your data object so it should look something like this

![screen shot 2018-01-30 at 16 16 01](https://user-images.githubusercontent.com/4705281/35574007-f32189da-05d8-11e8-9a90-a7b8ece090b6.png)

**Comment by annslittleflower** [comment]
okay, just hardcoded array of arrays, not working( i think maybe the problem is because i render this function in some wrong way, dont you think so?

**Comment by securedeveloper** [comment]
It could be a reason, Please try to use `class` and `component` style from React,
```javascript
class Hello extends React.Component {
  render() {
    return <div>Hello {this.props.name}</div>;
  }
}
```

Please check this fiddle for a reference,
[https://jsfiddle.net/reactjs/69z2wepo/](https://jsfiddle.net/reactjs/69z2wepo/)

**Comment by annslittleflower** [comment]
it works man)))))))))))))))))))))))))))))))))))))))))))))))))
and works without classes
problem was i was just calling the function like in the air, this function wanted to be like in the DOM or something. Here is algorithm how i  solved this issue:
1) create a function that simply does setState({needExport: true})
2) create a function like in this doc with Excel components
3) somewhere in your parent component in render use this:
`{this.state.exportNeed && this.excel()}`

Now is better but there is no automatic download of the generated file, when i find out how to do this - i will write below this comment.
BTW thank you for spending so much time for me man) have a nice day)

**Comment by annslittleflower** [comment]
it works man)))))))))))))))))))))))))))))))))))))))))))))))))
and works without classes
problem was i was just calling the function like in the air, this function wanted to be like in the DOM or something. Here is algorithm how i  solved this issue:
1) create a function that simply does setState({needExport: true})
2) create a function like in this doc with Excel components
3) somewhere in your parent component in render use this:
`{this.state.exportNeed && this.excel()}`

Now is better but there is no automatic download of the generated file, when i find out how to do this - i will write below this comment.
BTW thank you for spending so much time for me man) have a nice day)

**Comment by annslittleflower** [comment]
Okay i finished everything, thats how i did automatic download of document:

`  excel() {

    setTimeout(() => {
      this.deleteDownloadButton();
    }, 50);

    return (

      <ExcelFile>
        <ExcelSheet data={this.state.entities.results} name="Orders">
          <ExcelColumn label="Name" value="name" />
          <ExcelColumn label="Created At" value="createdAt" />
        </ExcelSheet>
      </ExcelFile>
    )



  }`

`  deleteDownloadButton() {
    let aTags = document.getElementsByTagName("button");
    let searchText = "Download";
    let found;

    for (let i = 0; i < aTags.length; i++) {
      if (aTags[i].textContent == searchText) {
        found = aTags[i];
        break;
      }
    }

    if(found) {
      found.click();
      found.remove();
    }

  }`


This code means -- render button, click on it and delete it
But there is two more issues though - document is called "download" and i cannot change the name,
and the second one is there is no id or class on the download button, please review the deleteDownloadButton method to see how not comfortable i had to delete button. But nevertheless it all works and im happy) please consider fixing new issues i found, it will be really useful features for this package users))))

**Comment by securedeveloper** [comment]
Thank you for posting your solution, This might help somebody with similar conditions,

About styling download button, I it possible to pass your own custom element and you can assign any class/id to that component, to do so,
```javascript
<ExcelFile filename="YourFileName.xlsx" element={(<button className="YourCSSClassHere"> Download Report </button>)}> ....... </ExcelFile>
```

I am surely gonna add this in documentation on this weekend, 

Happy Coding 👨‍💻

**Comment by annslittleflower** [comment]
oh i did not know about such features its really-really nice, thanks for pointing to them)
please update your doc for others, i am pretty sure lots of people wanted to have those features in their apps)

**Comment by denvist** [comment]
I cannot understand that i'm doing wrong:

```
import React from 'react';
import { ExcelFile, ExcelSheet } from 'react-data-export';

export default class SampleComponent extends React.Component {
	render() {
		const dataSet1 = [
		    {
		        name: "Johson",
		        amount: 30000,
		        sex: 'M',
		        is_married: true
		    },
		    {
		        name: "Monika",
		        amount: 355000,
		        sex: 'F',
		        is_married: false
		    },
		    {
		        name: "John",
		        amount: 250000,
		        sex: 'M',
		        is_married: false
		    },
		    {
		        name: "Josef",
		        amount: 450500,
		        sex: 'M',
		        is_married: true
		    }
		];


		return (
			<ExcelFile filename="YourFileName.xlsx">
				<ExcelSheet data={dataSet1} />
			</ExcelFile>
		)
	}
}
```

I have got this error:

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
> 
> Check the render method of `SampleComponent`.

**Comment by annslittleflower** [comment]
try to add columns in your return, i think that is the problem

**Comment by denvist** [comment]
Nope:
> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
> 
> Check the render method of `SampleComponent`.

```
import React from 'react';
import { ExcelFile, ExcelSheet } from 'react-data-export';

export default class SampleComponent extends React.Component {
	render() {
		const dataSet1 = 
		[{
			columns: ["Name", "Created At"],
			data: [
				["Name1", "28-01-2018"],
				["Name2", "27-01-2018"]
			]
		}];


		return (
			<ExcelFile filename="YourFileName.xlsx">
				<ExcelSheet data={dataSet1} />
			</ExcelFile>
		)
	}
}
```

**Comment by denvist** [comment]
Full example:
```
import React from 'react';
import ReactDOM from 'react-dom';
import { ExcelFile, ExcelSheet } from 'react-data-export';

class SampleComponent extends React.Component {
	render() {
		const dataSet1 = [{
			columns: ["Name", "Created At"],
			data: [
				["Name1", "28-01-2018"],
				["Name2", "27-01-2018"]
			]
		}];


		return (
			<ExcelFile filename="YourFileName.xlsx">
				<ExcelSheet data={dataSet1} />
			</ExcelFile>
		)
	}
}

ReactDOM.render(
	<SampleComponent />,
	document.getElementById("root")
)
```

Error:

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
> 
> Check the render method of `SampleComponent`.
> ▶ 26 stack frames were collapsed.

```
./src/index.js
src/index.js:18
  15 | 	}
  16 | }
  17 | 
> 18 | ReactDOM.render(
  19 | 	<SampleComponent />,
  20 | 	document.getElementById("root")
  21 | )
```

**Comment by securedeveloper** [comment]
@denvist Your last code looks perfect. you just need to change property `data` to `dataset`,

so your code will look something like this,
```js
<ExcelSheet dataSet={dataSet1} />
```

Hopefully this will solve your issue.

**Comment by denvist** [comment]
@securedeveloper same error

**Comment by annslittleflower** [comment]
google says it is import error, so my other theory you import stuff in some bad way, your SampleComponent is undefined

**Comment by securedeveloper** [comment]
Thank you @annslittleflower for your time. 
Thank you @denvist you actually pointed out one more possible feature (which is default naming of ExcelSheets like MS Excel does like Sheet1, Sheet2 etc. )

I checked your script and I found 2 issues there,

**1. Importing is not correct**
   The way you are currently importing is `import { ExcelFile, ExcelSheet } from 'react-data-export';`
  But two possible import ways for you could be `import {default as ExcelFile, ExcelSheet } from 'react-data-export';` or `import ExcelFile, { ExcelSheet } from 'react-data-export';`

**2. You need to add name property in your `ExcelSheet` Component call.**
  So your code might be something like this,

```js
import React from 'react';
import ReactDOM from 'react-dom';
import { default as ExcelFile, ExcelSheet } from 'react-data-export';

class SampleComponent extends React.Component {
	render() {
		const dataSet1 = [{
			columns: ["Name", "Created At"],
			data: [
				["Name1", "28-01-2018"],
				["Name2", "27-01-2018"]
			]
		}];


		return (
			<ExcelFile filename="YourFileName.xlsx">
				<ExcelSheet dataSet={dataSet1} name="MiniDatabase" />
			</ExcelFile>
		)
	}
}

ReactDOM.render(
	<SampleComponent />,
	document.getElementById("root")
)
```

PS: it seems you are using react starter kit which has own set of scripts, so you don't need to worry about webpack config and it is being taken care by those scripts.

Hopefully this will solve your issue. Plz acknowledge if it works for you.

**Comment by denvist** [comment]
@securedeveloper thank you for your explanation! I need more to learn about import/export functionality. Tomorrow i will check your solution.

**Comment by securedeveloper** [comment]
@denvist still curious if that works for you if so I will update documentation accordingly on this weekend.

**Comment by denvist** [comment]
@securedeveloper yes, it's work!

btw: `import * from 'react-data-export'` arise importing error

**Comment by b-asaf** [comment]
@securedeveloper @denvist 
I tried to run the code above (on a new app using `npx create-react-app my-app`) and the code does not run, I did not even got to the excel.
I looked for a solution for export failure - see issue #89
