### ISSUE TITLE
Change download button title

### ISSUE THREAD

**Issue by escarabin** [securedeveloper/react-data-export#26]
Hi,

Thanks a lot for your work on this great plugin. I would like to change the default button "Download" text and there is nothing in the doc mentioning that, I have made tons of research ? Could you please help me 🙏🏻

Thanks a lot for your help,

Cheers

**Comment by securedeveloper** [comment]
Hello @escarabin ,
You can pass `<ExcelFile ....  element={<button>Download Report</button>}> ...` and you are done, work on documentation in in progress.
