### ISSUE TITLE
hide the download button

### ISSUE THREAD

**Issue by rajeshgutta** [securedeveloper/react-data-export#30]
Hi,

Thanks for building this awesome package. I want to make a small change where we give a prop to hide the download button. So if we have a prop `hideElement` set to true on `ExcelFile`, we directly download the file without rendering the download button. I made the change and have a branch ready. Please let me know how I can push the changes and create a Pull request for this.

**Comment by securedeveloper** [comment]
Hello @rajeshgutta, I am happy that you wish to contribute to this project. Please follow [these rules](https://github.com/securedeveloper/react-data-export/blob/master/CONTRIBUTING.md) to contribute, and let me know if you are still unable to do it.

**Comment by securedeveloper** [comment]
We just released you change in our latest deployment 🎉 ㊗️

**Comment by ganesh-sanap** [comment]
@securedeveloper, @rajeshgutta 
Can we show/hide or disable download button based on the length of data array (disable button if array is empty and enable button click and download file if there is data in array)?
