### ISSUE TITLE
Error when installing API

### ISSUE THREAD

**Issue by diegovasquesmellet** [securedeveloper/react-data-export#41]
I'm facing an issue when trying to install latest version of react-data-export.
I've added `"react-data-export": "^0.3.7"` to my POM.xml and I'm receiving the following error:
`[ERROR] npm ERR! Error while executing:`
`[ERROR] npm ERR! C:\Program Files (x86)\Git\bin\git.EXE ls-remote -h -t https://github.com/securedeveloper/js-xlsx.git`
`[ERROR] npm ERR!` 
`[ERROR] npm ERR! fatal: unable to access 'https://github.com/securedeveloper/js-xlsx.git/': Could not resolve host: github.com`
`[ERROR] npm ERR! `
`[ERROR] npm ERR! exited with error code: 128`

I had previously installed version `0.3.2` and was working fine.
Is someone having similar issues?

Thanks.

**Comment by securedeveloper** [comment]
Hello @diegovasquesmellet can you please share your `config` file, seems like you have internet connection problem,

**Comment by juanpicado** [comment]
@diegovasquesmellet could you try with `npm install` out of maven environment to see whether works correctly?

**Comment by diegovasquesmellet** [comment]
If by config you meant my pom.xml, please check below:

<plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <configuration>
                    <workingDirectory>src/main/webapp/static/app</workingDirectory>
                </configuration>
                <version>1.5</version>
                <executions>
                    <execution>
                        <id>install node and npm</id>
                        <goals>
                            <goal>install-node-and-npm</goal>
                        </goals>
                        <configuration>
                            <nodeVersion>v4.6.0</nodeVersion>
                            <npmVersion>5.3.0</npmVersion>
                          </configuration>
                    </execution>
                    <execution>
                        <id>npm install</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        
                        <configuration>
                            <arguments>install</arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>npm run build</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <configuration>
                            <arguments>run build</arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Comment by diegovasquesmellet** [comment]
If by config file you meant my pom.xml, please check below:
`<plugin>`
                `<groupId>com.github.eirslett</groupId>`
                `<artifactId>frontend-maven-plugin</artifactId>`
                `<configuration>`
                    `<workingDirectory>src/main/webapp/static/app</workingDirectory>`
               ` </configuration>`
               ` <version>1.5</version>`
                `<executions>`
                    `<execution>`
                        `<id>install node and npm</id>`
                        `<goals>`
                            `<goal>install-node-and-npm</goal>`
                        `</goals>`
                        `<configuration>`
                            `<nodeVersion>v4.6.0</nodeVersion>`
                            `<npmVersion>5.3.0</npmVersion>`
                   `</configuration>`
                    `</execution>`
                    `<execution>`
                        `<id>npm install</id>`
                        `<goals>`
                            `<goal>npm</goal>`
                        `</goals>`
                        `<!-- Optional configuration which provides for running any npm command -->`
                        `<configuration>`
                            `<arguments>install</arguments>`
                        `</configuration>`
                    `</execution>`
                    `<execution>`
                        `<id>npm run build</id>`
                        `<goals>`
                            `<goal>npm</goal>`
                        `</goals>`
                        `<configuration>`
                            `<arguments>run build</arguments>`
                        `</configuration>`
                   `</execution>`
                `</executions>`
            `</plugin>`

**Comment by diegovasquesmellet** [comment]
@juanpicado tried outside maven environment and it was the same error.

**Comment by diegovasquesmellet** [comment]
Weird is that this is only happening with the `xlsx' API.
I've tried for testing purpose installing separately the other dependency from `react-data-export` which is the `file-saver` and it was installed correctly..

**Comment by securedeveloper** [comment]
@diegovasquesmellet it seems like you are using node version `<5` which it making problem, please try to update node version if possible, and let us know if it will fix your issue. otherwise we can dig into issue with more details.

**Comment by securedeveloper** [comment]
@diegovasquesmellet Did you manage to solve the issue ?

**Comment by diegovasquesmellet** [comment]
Just tried.
Updated node to version 9.11.1 and npm to 5.6.0 and it's the same issue.

**Comment by diegovasquesmellet** [comment]
I'm trying to check with my infrastructure team if this could be the firewall blocking the access to GitHub host.

**Comment by diegovasquesmellet** [comment]
Actually: `xlsx-style: 0.8.13` ?

**Comment by securedeveloper** [comment]
Hi @diegovasquesmellet we used our own fork of `xlsx` untill the original repo start supporting `cell` styling, we didn't use `xlsx-style` because of it's supporting nature they might have deprecate it any time. Will investigate and might publish this temporarily on npm. if that might help.

**Comment by diegovasquesmellet** [comment]
Is it possible to publish this fork of yours into NPM?

**Comment by diegovasquesmellet** [comment]
My issue is that I can't install API's that are located outside my companies network. If the `xlsx` could be published on NPM it would be great.

**Comment by diegovasquesmellet** [comment]
In the meantime; You're saying that `xlsx-style` do not support spreadsheet styling?

**Comment by securedeveloper** [comment]
Well, `xlsx-style` support cell styling and I fork from them, but just to make sure things are maintained and not broken we needed our own fork and yes it is possible to publish with `npm`

**Comment by diegovasquesmellet** [comment]
Well, it would be great to have this published on NPM in a non temporarily status.
Thank you all for the support!

**Comment by diegovasquesmellet** [comment]
When would you think is it possible to have the API published on NPM?

**Comment by securedeveloper** [comment]
Today I will publish it so it will be ready.

**Comment by diegovasquesmellet** [comment]
That will be awesome! Thanks!

**Comment by diegovasquesmellet** [comment]
It was published?

**Comment by diegovasquesmellet** [comment]
@securedeveloper any updats?
Thanks.

**Comment by diegovasquesmellet** [comment]
Great. I'll be waiting for it so I can test! Thanks.

**Comment by diegovasquesmellet** [comment]
What do you mean by “break the normal pipeline”?

**Comment by securedeveloper** [comment]
@diegovasquesmellet Can you please try version 0.4.2, I am quite sure it will work for you too.

I just break mistakenly project pipeline, but is OK now.

**Comment by diegovasquesmellet** [comment]
I see in your package.json has no changes related to the xlsx. Why do you think it will work?
Tomorrow I can try and let you know

**Comment by diegovasquesmellet** [comment]
@securedeveloper Same error :(
`[ERROR] npm ERR! fatal: unable to access 'https://github.com/securedeveloper/js-xlsx.git/': Could not resolve host: github.com`

**Comment by securedeveloper** [comment]
Hi @diegovasquesmellet , can you please try to clone `https://github.com/securedeveloper/js-xlsx.git/` locally and see it that works,

**Comment by diegovasquesmellet** [comment]
Even if I do this and works for me locally, it won't help when deploying the application because firewall will block the github host :(
Is really a problem to add this fork of yours into NPM environment?

**Comment by diegovasquesmellet** [comment]
It will be possible to add this fork on NPM environment? If not its ok and I appreciate the support, i just need to know if I'll have to look for another API.

Thanks

**Comment by securedeveloper** [comment]
@diegovasquesmellet the published package is ready, I just need to change configuration on library. It will be ready on Weekend. Because of testing in different environments it's gonna take a bit. But you will definitely have a solution till this weekend. Thanks :)

**Comment by diegovasquesmellet** [comment]
Sounds perfect! Thank you all.

**Comment by diegovasquesmellet** [comment]
Any news?
Thanks.

**Comment by diegovasquesmellet** [comment]
ping.

**Comment by securedeveloper** [comment]
Hi @diegovasquesmellet because the original package does not allow such distribution to `npm` I can only use their package or a fork, I'm in contact and we will have something very soon.

**Comment by diegovasquesmellet** [comment]
Ok. Thanks. :)

**Comment by diegovasquesmellet** [comment]
No good news here, right? :(

**Comment by diegovasquesmellet** [comment]
Thanks :)

**Comment by jsmani81** [comment]
I am also facing same issue. In Jenkins while building it is throwing same error as mentioned. do we have any work around for this.

**Comment by jsmani81** [comment]
error An unexpected error occurred: "Refusing to download the git repo {\"hostname\":\"github.com\",\"protocol\":\"https:\",\"repository\":\"https://github.com/securedeveloper/js-xlsx.git\"} over HTTPS without a commit hash - possible certificate error?".

**Comment by TobalOW** [comment]
same error here

**Comment by lvlw** [comment]
same error here +1

**Comment by securedeveloper** [comment]
@diegovasquesmellet, @jsmani81, @TobalOW we have a new version which will fix these issues, we are going to release after this week. It's still in testing phase.

**Comment by touhami92** [comment]
same error with current last version (0.4.2)

**Comment by diegovasquesmellet** [comment]
Guys, give up, they’re not going to fix it. I’ve reported this issue 5 months ago and it’s on “will be released next week” state.

Just find yourselves another API.

**Comment by securedeveloper** [comment]
@diegovasquesmellet I know it's been hard since I don't have much choice with the libraries (in my case I'm using `xlsx` and they don't have an open source which can support excel styling and other requirements. There are a couple of things which are still under development (as I wasn't working on this library for a while and unfortunately, Jira doesn't have any tool to change the status if someone is not working), the point about next week release was a try where we try to release `xlsx` altogether with  `react-data-export` which doesn't work. My current solution was a complete write-down of Microsoft Excel's API in JS, which I have been studying for 2 months for now and I am in a position to start working on it from now on, 

Although I updated my readme to reflect upcoming changes in the library. But I didn't mention any exact time (approximately it's gonna take around a month), this time I'm writing down the whole excel API by myself so there will be no dependency (also blocking and Installation issues). 

All I need co-operation from you guys and would be great if anyone can help me boost the development.

**Comment by vpotluri1217** [comment]
Just FYI, This is still happening...

**Comment by vpotluri1217** [comment]
fatal: unable to access 'https://github.com/securedeveloper/js-xlsx.git/': Failed to connect to github.com port 443: Timed out
