### ISSUE TITLE
PoSh Newbie 

### ISSUE THREAD

**Issue by FBBZ** [securedeveloper/react-data-export#49]
I am brand new to PoSh and I am looking for some assistance with, I am assuming an easy for you all script.  I have to pull data from Excel (ONLY 2 columns of LastName, FirstName, 15 Rows) into PoSh, then into a new Excel spreadsheet, putting the 2 columns of data into 1 column. Any help would be grealy appreciated!

**Comment by securedeveloper** [comment]
Hey @FBBZ, Yes it sounds pretty easy, put this package is meant to export only. it has a dependency `xlsx` you can use to read `excel file` and then you can export as you want. Hope this help.

**Comment by FBBZ** [comment]
Thank You, it does.

-------- Original message --------From: Afzal Ahmad <notifications@github.com> Date: 5/8/18  3:38 AM  (GMT-05:00) To: securedeveloper/react-data-export <react-data-export@noreply.github.com> Cc: FBBZ <zach15f@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [securedeveloper/react-data-export] PoSh Newbie (#49) 
Hey @FBBZ, Yes it sounds pretty easy, put this package is meant to export only. it has a dependency xlsx you can use to read excel file and then you can export as you want. Hope this help.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/securedeveloper/react-data-export","title":"securedeveloper/react-data-export","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/securedeveloper/react-data-export"}},"updates":{"snippets":[{"icon":"PERSON","message":"@securedeveloper in #49: Hey @FBBZ, Yes it sounds pretty easy, put this package is meant to export only. it has a dependency `xlsx` you can use to read `excel file` and then you can export as you want. Hope this help."}],"action":{"name":"View Issue","url":"https://github.com/securedeveloper/react-data-export/issues/49#issuecomment-387313579"}}}
