### ISSUE TITLE
Is there any way to achieve a "colspan" feature?

### ISSUE THREAD

**Issue by pedrobrost** [securedeveloper/react-data-export#50]
I need to group two columns in one, do you know if I can try something to achieve this?

It would be amazing to have a colspan feature :)

Thanks!

**Comment by securedeveloper** [comment]
Hi @pedrobrost, We are using a forked version of `js-xlsx` library and for the moment it does not support colspan [How to write merged Cells #92](https://github.com/SheetJS/js-xlsx/issues/92),

But, with our forked version, you can get the merged styled look by applying style to it (eg, white background and/or no borders),

Hope this will help, re-open this issue if you need further help.
