### ISSUE TITLE
First fetch data from server then export xlsx file with same click

### ISSUE THREAD

**Issue by arpitprod** [securedeveloper/react-data-export#54]
First I want to fetch data with API then that data should download with react-data-export. 
For this, I want to use single button for both work. 

this time, I'm using like this - 
`<Button onClick={this.fetchData}>Fetch Data</Button>`

```
fetchData() {
  axios.get('api_link')
    .then(({data}) => {
      this.setState({data})
    })
}
```
and then Download data - 

```
<ExcelFile element={<button>Download Data</button>}>
	<ExcelSheet data={data} name="Employees">
		<ExcelColumn label="Name" value="name"/>
		<ExcelColumn label="Wallet Money" value="amount"/>
		<ExcelColumn label="Gender" value="sex"/>
		<ExcelColumn label="Marital Status" value={(col) => col.is_married ? "Married" : "Single"}/>
	</ExcelSheet>
</ExcelFile>
```

but Buttons will show 2 times. it's not good looking for users. 

So, How can I fetch and download data with only one click ?

**Comment by arpitprod** [comment]
We can use like this

````
<Button onClick={this.fetchData}>Fetch Data</Button>
{this.state.data != null ? 
	<ExcelFile element={<button>Download Data</button>} hideElement={true}>
		<ExcelSheet data={data} name="Employees">
			<ExcelColumn label="Name" value="name"/>
			<ExcelColumn label="Wallet Money" value="amount"/>
			<ExcelColumn label="Gender" value="sex"/>
			<ExcelColumn label="Marital Status" value={(col) => col.is_married ? "Married" : "Single"}/>
		</ExcelSheet>
	</ExcelFile>
        :
        null
}
````

**Comment by securedeveloper** [comment]
Hi @arpitprod in your case you can use `hideElement` property, you can call exactly like above code and it will work.

**Comment by arpitprod** [comment]
@securedeveloper How to add sheet style like this image with json dataset, there thousands rows so, I can't add style in every cell like example 4

![html-table-example-2](https://user-images.githubusercontent.com/19798516/40226976-d99dc894-5aaa-11e8-83c6-5985f11d26e0.gif)

**Comment by thinhnk** [comment]
@arpitprod  after the first download => set state data = null.
That is my trick.

**Comment by securedeveloper** [comment]
@arpitprod Please go either with the solution @thinhnk suggested or use a callback which delivers prepared data each time instead of state.

**Comment by neeleshbisht99** [comment]
How to set state data = null after the first download ??

**Comment by arpitprod** [comment]
@neeleshbisht99 when you will be click on download button, call a function inside button with onClick and set data null with `setState`/`useState`
`this.setState({data: null})`
or if you are using function component 
and you are using like `const [data, setData] = useState(null);`
then you can apply with `setData(null);`

**Comment by neeleshbisht99** [comment]
Thanks, that worked fine, but it would be better if there is an event listener, because it's very common case I guess. Or if we can override the button click.

**Comment by neeleshbisht99** [comment]
Files gets downloaded twice with the above method @arpitprod @securedeveloper

**Comment by javaGuy33** [comment]
> Hi @arpitprod in your case you can use `hideElement` property, you can call exactly like above code and it will work.

Hi @securedeveloper, when I am trying to hide the button using 'hideElement' property. The excel file is downloading twice. Did you come across such king of issue?

**Comment by venkateshtechefficio** [comment]
The excel files is downloading 2 times. do we have any solution, thank you
