### ISSUE TITLE
TypeError: s.t.match is not a function

### ISSUE THREAD

**Issue by arpitprod** [securedeveloper/react-data-export#55]
I'm using 'Excel Export with custom cells style' example and adding dynamic content. When I'm using your example then excelsheet is downloading with correct data but when I'm passing dynamic data then it's showing error

`TypeError: s.t.match is not a function`

If I restart my server then many times this error not showing but data also not fetch in excelsheet after download 

Sample code is here

````
import React, {Component} from 'react';
import ReactExport from 'react-data-export';
import _ from 'underscore'

const ExcelFile = ReactExport.ExcelFile;
const ExcelSheet = ReactExport.ExcelFile.ExcelSheet;

class App extends Component {
	constructor(props) {
		super(props);

		this.state = {
			multiDataSet: []
		}
	}

	componentDidMount() {
		this.callFakeApi()
	}

	callFakeApi() {
		fetch('https://jsonplaceholder.typicode.com/posts')
		.then(response => response.json())
		.then(json => {
			console.log(json)
			this.convertDataFormat(json)
		})
	}

	convertDataFormat(json) {
		const jsonHeader = _.keys(json[0])
		const data = json.map((obj, i) => {
			const array = []
			if (i % 2 === 0) {
				var style = {fill: {patternType: "solid", fgColor: {rgb: "FFFF0000"}}}
			} else {
				var style = {}
			}
			jsonHeader.map((columnName) => {
				array.push({value: obj[columnName], style})
			})
			return array
		})
		const multiDataSet = [{columns: jsonHeader, data: data}]
		console.log(multiDataSet)
		this.setState({
			multiDataSet
		})
	}

	render() {
		return (
			<div>
				<ExcelFile element={<button>Download Data With Styles</button>}>
					<ExcelSheet dataSet={this.state.multiDataSet} name="Organization"/>
				</ExcelFile>
			</div>
		);
	}
}

export default App

````

**Comment by arpitprod** [comment]
@securedeveloper same issue with this code also

`TypeError: s.t.match is not a function`

**Comment by securedeveloper** [comment]
I'll check it and will get back to you after some debugging.

**Comment by arpitprod** [comment]
ok

**Comment by minhtd1981** [comment]
Hi @securedeveloper,

I'd like to contribute a little bit on this project. This error occurred when s.t is not a string for instance a number.

If you are using dataSet, getCell() should be modified a little bit
    } else if (typeof v === 'object') {
        cell.v = v.value;
        cell.s = v.style;
        if (typeof v === 'number') cell.t = 'n'
    }

If you are using data, createSheetData() and excelSheetFromAoA() should be modified a little bit
sheetRow.push({ value: ... itemValue, style: style })
and
    } else if (typeof cell.v === 'object') {
                const { value, style } = cell.v;
                cell.v = value;
                cell.s = style;
                if (typeof value === 'number') cell.t = 'n'
    } else {
so that you can set the style via ExcelColumn.

Thanks,

**Comment by securedeveloper** [comment]
Hi @minhtd1981, 

Nice to have you on board, and pointing out the solution. Please create a PR on base of your solution and this weekend I will make sure to merge all feedback solutions and will publish next release after testing.

**Comment by gmonte** [comment]
Try set cell value always as a string (not number or null or undefined or anything). This work for me

**Comment by minhtd1981** [comment]
@gmonte then you cannot use numFmt ;-)
@securedeveloper I will try to arrange time to do that

**Comment by shmilyoo** [comment]
> Try set cell value always as a string (not number or null or undefined or anything). This work for me

the bug is due to xlsx.js, for the line s.t.match.  when s.t is not string, it will be an error.
according to @gmonte , not only the cell ,but also the header title, should be string.
I came across the but, because my table header, on of it , is a react element.
be ware of it!

**Comment by wahyupriadi-edts** [comment]
I got this error and found out one of my variable passed to multiDataSet is not number or string.
So, either number or string still works, just make sure the type of data you define is one of them.

**Comment by ashok-2695** [comment]
@wahyupriadi-edts  all variables are in string or number but it's not working it showing error s.t.match is not a function
Any solution for this ??

**Comment by aviyi** [comment]
@ashok-2695  all the value should be string . 
I used toString and now it's work
