### ISSUE TITLE
No git binary found in $PATH

### ISSUE THREAD

**Issue by aakashgupta0205** [securedeveloper/react-data-export#58]
When I try to install react-data-export, npm complains that no git binary found. Usually npm does not require git executables to be present on the system. However, if I do put git in my path it works. It is a huge impediment during deployment because I can't guarantee that git client is installed on the server.

![issue](https://user-images.githubusercontent.com/15355381/41708794-23d1cfda-7574-11e8-8aa3-fa3078022bf2.png)

**Comment by securedeveloper** [comment]
Hi @aakashgupta0205 I'm currently investigating this issue, will get back to you with a solution, please feel free to contribute if you find any suitable solution.

**Comment by securedeveloper** [comment]
duplicate #41
