### ISSUE TITLE
How to set bold for ExcelColumn

### ISSUE THREAD

**Issue by paolospag** [securedeveloper/react-data-export#61]
Hi,
I'm looking for a package that exports data from HTML table to Excel file and this module does exactly what I wanted.

I'm using this examples:
https://github.com/securedeveloper/react-data-export/blob/master/examples/with_custom_download_element.md
because my case is very similar, but I want to set bold font-weight in the first row of Excel file (i.e. the headings).

Is there a way to do that in ExcelColumn component or other way?
Thanks

**Comment by securedeveloper** [comment]
Hi @paolospag,

Please check this example [https://github.com/securedeveloper/react-data-export/blob/master/examples/styled_excel_sheet.md](https://github.com/securedeveloper/react-data-export/blob/master/examples/styled_excel_sheet.md)

This should solve your requirement.

**Comment by OmkarKumbare** [comment]
Here is simple example for export excel file using react


Used exceljs for implementation

https://stackblitz.com/edit/react-export-to-excel
