### ISSUE TITLE
Recommended process for conditional columns (getting corrupt file)

### ISSUE THREAD

**Issue by hlyford** [securedeveloper/react-data-export#62]
Awesome library. Thanks for the work on this!

I think a common use case is that the user only want certain columns on their export. I accomplished this via an array of columns with each column being added if it matches some conditional (because you get errors if you try to put a conditional as a child of <ExcelFile /> in the jsx). Example of how I did this:

```
// column you always want to include
let allColumns = [<ExcelColumn label="Name" value="name" key="name" />]  

// conditional adding of additional columns passed on props
if (this.props.exportOptions.email) {
    allColumns.push(<ExcelColumn label="Email" value="email" key="email" />);
}

// finally, map the columns
<ExcelSheet data={candidates}>
    {allColumns.map(el => el)}
</ExcelSheet>
```

ISSUE: 
When I export the file on a machine that has Excel, I get an error message from Excel that the file is corrupted.

QUESTIONS:
If there is a better way - or this is the preferred way - can the README be updated? (My error may be caused by something else)
If this is likely the reason I am seeing my error, could you let me know why?

**Comment by securedeveloper** [comment]
Hi @hlyford,

This is the issue you will get if there is a mismatch of datatype, I am not sure which data type you are getting at the end but It is for sure data type mismatch.

Alternatively you can try [export with dataset](https://github.com/securedeveloper/react-data-export/blob/master/examples/simple_excel_export_02.md) or [multi dataset export](https://github.com/securedeveloper/react-data-export/blob/master/examples/styled_excel_sheet.md).
