### ISSUE TITLE
Columns Key

### ISSUE THREAD

**Issue by arif25169** [securedeveloper/react-data-export#63]
Is there any way to user the column key and title like this
`  {title: "Name", dataKey: "name"},`  for multidataset.

**Comment by securedeveloper** [comment]
@arif25169 with [simple excel export](https://github.com/securedeveloper/react-data-export/blob/master/examples/simple_excel_export_01.md) you can define `label` and `value` keys for the columns, 
However with big data set it is not possible yet. But I'll include it to my next plan notes and will include in in next release.
