### ISSUE TITLE
fs missing

### ISSUE THREAD

**Issue by b0gd4n** [securedeveloper/react-data-export#65]
Hey there,

Trying to follow the simple example, but I am getting the following error while compiling:

`* fs in ./node_modules/xlsx/xlsx.js, ./node_modules/xlsx/ods.js`

I tried running `npm install --save fs` but it has the same result.

**Comment by securedeveloper** [comment]
in webpack configuration file (or any other entry configuration file), set `node: {fs: 'empty'},` and it will work.

**Comment by josealvaradoo** [comment]
Thank you @securedeveloper 
it's working.

**Comment by freddiemixell** [comment]
@securedeveloper this helped me out as well thanks!
