### ISSUE TITLE
Can excelColumn value support a.b.c ?

### ISSUE THREAD

**Issue by plainnany** [securedeveloper/react-data-export#71]
hi, there is my dataSource , just Like
```
const dataSource = [{
  name: 'John', 
  age:  18,
  info: {
    work: 'programmer',
    location: 'China'
  }
}, {
  name: 'Nany', 
  age:  18,
  info: {
    work: 'programmer',
    location: 'USA'
  }
}]
```

Is possible to export info.location ?
I try to  ` <ExcelColumn label="location" value="info.location"} />`, but it doesn't work

**Comment by securedeveloper** [comment]
@plainnany please use `<ExcelColumn label="location" value="(col) => col.info.location"} />`

**Comment by securedeveloper** [comment]
I hope this will work, I'm closing this issue, feel free to re-open if you still have any related issues. :)
