### ISSUE TITLE
Nested objects

### ISSUE THREAD

**Issue by Akshara89** [securedeveloper/react-data-export#73]
**Json List for data**
[{
id: 1,
name: "Bariatric Bed AH 1",
img_thumb: [  "tn-arjo-huntleigh-bariatric-bed-2.jpg"	],
asset_positions: [ {
id: 2,
name: John
}
]},
{
id: 2,
name: "Bariatric Bed AH 1",
img_thumb: [  "tn-arjo-huntleigh-bariatric-bed-2.jpg"	],
asset_positions: [ {
id: 2,
Name: Peter
}
]}
}
]

I want to get asset_positions.name .
I tried value=  {(col) => col.asset_positions.name}. But still it is not working.

**Comment by josealvaradoo** [comment]
You could make an object without nested objects from your original data, maybe on `componentWillMount` method

```
import data from "./data.json"

// Code

componentWillMount() {
    let array = []
    data.map(item => {
        const obj = {
            id: item.id,
            name: item.name,
            img_thumb: item.img_thumb,
           asset_positions_1_id: ,
           asset_position_1_name: ,
           asset_position_2_id: ,
           asset_position_2_name: ,

        array.concat(obj)
    })
    this.setState({ data: array })
}
```

You have to map each `asset_position` array. It is not a great solution, but is one. It would be ideal if the lib could use nested objects.

**Comment by securedeveloper** [comment]
@Akshara89 hopefully the snippet by @josealvaradoo will help you, if not please get back and we will help you. Thanks @josealvaradoo ❤️
