### ISSUE TITLE
ExcelColumn width and style prop - Feature

### ISSUE THREAD

**Issue by tiagohermano** [securedeveloper/react-data-export#82]
Pass a width prop to the ExcelColumn component.

#### My reason:
It would be nice to set the width for the column, so it can fit all the content inside the column's cells.
Maybe even implementing a prop for styling on ExcelColumn as well. I think it would be great being able to style the column titles.

**Comment by securedeveloper** [comment]
@tiagohermano we already have this feature, please refer to ([https://github.com/securedeveloper/react-data-export/blob/master/examples/styled_excel_sheet.md](https://github.com/securedeveloper/react-data-export/blob/master/examples/styled_excel_sheet.md))
