### ISSUE TITLE
Importing errors

### ISSUE THREAD

**Issue by igoriok1994** [securedeveloper/react-data-export#86]
Hi,

I can't resolve import errors. 

Webpack 4
React
Babel 6

![image](https://user-images.githubusercontent.com/37294916/47359451-7be84d80-d6d5-11e8-8a72-ee01a6deb4b4.png)

Added vendor
![image](https://user-images.githubusercontent.com/37294916/47359470-8acf0000-d6d5-11e8-9cdd-5871d7abac49.png)

Added external & node

![image](https://user-images.githubusercontent.com/37294916/47359498-97ebef00-d6d5-11e8-973e-349bcdb163ad.png)

Maybe I need to include react-data-export ir xlsx folder to my module rules?
![image](https://user-images.githubusercontent.com/37294916/47359549-bd78f880-d6d5-11e8-8a65-06d250281f4d.png)

**Comment by igoriok1994** [comment]
Solved by adding '../xlsx': 'var _XLSX' to webpack externals. 
![image](https://user-images.githubusercontent.com/37294916/47411743-6aa14e80-d772-11e8-8f31-2bbfa0dacbd4.png)

**Comment by securedeveloper** [comment]
@igoriok1994 glad you solved it,
